2024-11-07 20:17:49,289 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\Python\PycharmProjects\datas\tests_12_4.py", line 59, in test_run
    r = Runner(10)
        ^^^^^^^^^^
  File "D:\Python\PycharmProjects\datas\tests_12_4.py", line 9, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-07 20:17:49,291 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\Python\PycharmProjects\datas\tests_12_4.py", line 72, in test_walk
    r = Runner('Ходун', -5)
        ^^^^^^^^^^^^^^^^^^^
  File "D:\Python\PycharmProjects\datas\tests_12_4.py", line 14, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
